export type AreaEnum = 'ADMIN' | 'ESTADO_GENERICO' | 'COMERCIO'
    | 'PERFIL' | 'ERPS' | 'BENEFICIOS' | 'NIVEL' | 'CONDICION_NIVEL' | 'IDENTIFICACION' | 'TOPE_BENEFICIO'
    | 'COMPRARADOR' | 'TRANSACCION' | 'TIPOPAGO' | 'DESCUENTO' | 'DESCUENTO_PROMOCION' | 'VIAS';